version: 2

references:

  ubuntu_deps: &ubuntu_deps
    run:
      name: Install dependencies on Ubuntu.
      command: |
        apt-get update -qy
        apt-get install -y git python3-dev python3-pip curl
        pip3 install coveralls coverage

  arch_deps: &arch_deps
    run:
      name: Install dependencies on Arch Linux.
      command: |
        pacman -Syu --noconfirm python python-pip git base-devel curl
        pip install coveralls coverage

  install: &install
    run:
      name: Install.
      command: |
        pip3 install .
        pip3 install -r requirements-tests.txt

  test: &test
    run:
      name: Run tests.
      command: |
        python3 setup.py test

  deploy: &deploy
    run:
      name: PyPI deploy
      command: |
        pip3 install wheel setuptools --upgrade
        bash <(curl -fsSL https://raw.githubusercontent.com/iterait/ci-utils/master/pypi_deploy.sh)

  add_rw_key: &add_rw_key
    add_ssh_keys:
      fingerprints:
        - "3f:5e:04:8c:b9:95:0e:9a:b6:f5:06:02:6f:13:d7:f8"

  doc: &doc
    run:
      name: Generate documentation
      command: |
        bash <(curl -fsSL https://raw.githubusercontent.com/iterait/ci-utils/master/doc_deploy.sh)

  coverage: &coverage
    run:
      name: Report test coverage
      command: |
        coverage run setup.py test
        coverage report
        COVERALLS_REPO_TOKEN=Qxd7pvYlxVRvyJMsblAPcEWmwZdedoqgh coveralls

jobs:

  test_ubuntu_latest:
    docker:
      - image: ubuntu:latest
    working_directory: ~/emloop
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_ubuntu_rolling:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/emloop
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_archlinux:
    docker:
      - image: archimg/base-devel
    working_directory: ~/emloop
    steps:
      - *arch_deps
      - checkout
      - *install
      - *test

  coverage:
    docker:
      - image: archimg/base-devel
    working_directory: ~/emloop
    steps:
      - *arch_deps
      - checkout
      - *install
      - *coverage

  generate_documentation:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/emloop
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *add_rw_key
      - *doc

  deploy:
    docker:
      - image: archimg/base-devel
    working_directory: ~/emloop
    steps:
      - *arch_deps
      - checkout
      - *deploy

workflows:

  version: 2
  test-doc-deploy:
    jobs:
      - test_ubuntu_latest
      - test_ubuntu_rolling
      - test_archlinux
      - coverage:
          requires:
            - test_ubuntu_latest
            - test_ubuntu_rolling
            - test_archlinux
      - generate_documentation:
          filters:
            branches:
              only: master
          requires:
            - test_ubuntu_latest
            - test_ubuntu_rolling
            - test_archlinux
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test_ubuntu_latest
            - test_ubuntu_rolling
            - test_archlinux
            - generate_documentation
            - coverage

  nightly-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - dev
    jobs:
      - test_ubuntu_latest
      - test_ubuntu_rolling
      - test_archlinux
